### ISSUE TITLE
None of the Wayland examples working on Fedora 25

### ISSUE THREAD

**Issue by namandixit** [eyelash/tutorials#2]
On Fedora 25, compiling any of the examples and running them gives this error:

`wl_registry@2: error 0: invalid version for global wl_compositor (2): 0 is not a valid version`

Changing the last argument in `wl_registry_bind` everywhere from 0 to 1 seems to work. 

(But since I basically started learning Wayland today, I am not sure if this is the right fix and hence an issue instead of pull request)

**Comment by eyelash** [comment]
It's been a while since I wrote these and I haven't really kept up with the changes to Wayland since then. Until I find the time to update these I suggest you to look at the [Weston examples](https://github.com/wayland-project/weston/blob/master/clients/simple-egl.c) and maybe the history of these files to figure out how to do things correctly (they were my main documentation when writing my examples anyway).
