### ISSUE TITLE
Blank green screen - nothing happens, even when a program connects

### ISSUE THREAD

**Issue by karatekid430** [eyelash/tutorials#5]
Enough said.

**Comment by eyelash** [comment]
What program are you testing with? Can you test with one of the Weston example clients?

**Comment by Zeng-Zer** [comment]
Same for me, nothing happens, green screen even though the compositor outputs in the terminal:
```
bind: compositor
bind: wl_shell
bind: seat
```
Tested with wayland-compositor and wayland-input from the tutorials

With weston-simple-egl:
```
has EGL_EXT_buffer_age and EGL_EXT_swap_buffers_with_damage
weston-simple-egl: clients/simple-egl.c:439: create_surfaceed.
[1]    11354 abort (core dumped)  weston-simple-egl
```

**Comment by eyelash** [comment]
The weston examples currently require the unstable v6 version of the xdg-shell protocol but my compositor only implements an older version of that protocol. A year ago the stable version of the xdg-shell protocol [was released](https://lists.freedesktop.org/archives/wayland-devel/2017-December/036037.html) and I wanted to update my compositor to that version but I decided to wait until the weston examples were updated to the stable version as well (there's a pull request [here](https://gitlab.freedesktop.org/wayland/weston/merge_requests/62)) so I could test my compositor against them.
So right now my plan is to wait until that pull request is merged and a new version of weston is released and then update the compositor to that version. Implementing the unstable v6 version of xdg-shell doesn't make sense to me now since I will eventually need to update to the stable version anyway.

**Comment by twaik** [comment]
Hi. Can you please fix the issue?

**Comment by twaik** [comment]
I have adapted your code for my purposes but it behaves a bit wrong. Can you please help me?

**Comment by eyelash** [comment]
Unfortunately [Debian](https://tracker.debian.org/pkg/weston) and Ubuntu are still on version 5.0 of Weston and I need version 6.0 to fix this bug. Right now I don't want to install a different disitribution just to fix this bug.

**Comment by twaik** [comment]
You do not need to install another distribution to update weston. You can build it on your pc.

**Comment by eyelash** [comment]
> You do not need to install another distribution to update weston. You can build it on your pc.

But that's almost as much effort as installing another distribution. Also I don't like to install things from source because it's hard to completely remove them afterwards.

**Comment by twaik** [comment]
"ninja install" for install and "ninja uninstall" for remove?
